name: CI
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ $default-branch ]
permissions:
    contents: read
jobs:
    build:
        name: "Tests ${{ matrix.php-version }} ${{ matrix.dependency-versions }} deps ${{ matrix.dependency-versions }}"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                # normal, highest, non-dev installs
                php-version: ['7.4', '8.0', '8.1']
                composer-options: ['--prefer-stable']
                dependency-versions: ['highest']
                include:
                    # testing lowest PHP version with lowest dependencies
                    - php-version: '7.4'
                      dependency-versions: 'lowest'
                      composer-options: '--prefer-lowest'
        steps:
            - uses: actions/checkout@v3

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: ${{ matrix.php-version }}

#            - name: Cache Composer packages
#              id: composer-cache
#              uses: actions/cache@v3
#              with:
#                  path: vendor
#                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#                  restore-keys: |
#                      ${{ runner.os }}-php-


            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Composer dependencies
              uses: ramsey/composer-install@v1
              with:
                  dependency-versions: ${{ matrix.dependency-versions }}
                  composer-options: --prefer-dist --no-progress

            - name: Run PHPUnit tests
              run: ./vendor/bin/simple-phpunit
